# SITE SETUP
appearance:
  mode: system
  color: indigo

marketing:
  seo:
    site_type: Person
    description: "Personal academic website"
  analytics:
    google_analytics: ""
  verification:
    google: ""

header:
  navbar:
    enable: true
    block: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Guanyi Yang"

footer:
  copyright:
    notice: "© {year} Guanyi Yang. All rights reserved."
    license:
      enable: false

locale:
  date_format: "Jan 2, 2006"

features:
  math:
    enable: false
  privacy_pack:
    enable: false
  
  homepage:
    type: "page"
    enabled: true
